[[themes]]
name = "swamp"
[themes.palette]
background = "#272316"
foreground = "#ebe0bb"
black = "#272316"
red = "#f87c2a"
green = "#acbb4f"
yellow = "#ec9f0d"
blue = "#48b8d0"
magenta = "#f76f8e"
cyan = "#65f69c"
white = "#9F8875"
bright_black = "#3a3124"
bright_red = "#cc005c"
bright_green = "#acbb4f"
bright_yellow = "#fbb323"
bright_blue = "#7dccde"
bright_magenta = "#bc4e78"
bright_cyan = "#8bf8b5"
bright_white = "#ebe0bb"
[themes.component_style]
block_title = { fg = "Red"  }
border = {}
playback_track = { fg = "Yellow", modifiers = ["Bold"] }
playback_artists = { fg = "Yellow", modifiers = ["Bold"] }
playback_album = { fg = "BrightRed" }
playback_metadata = { fg = "White" }
playback_progress_bar = { bg = "BrightBlack", fg = "Yellow" }
current_playing = { fg = "BrightMagenta", modifiers = ["Bold"] }
page_desc = { fg = "BrightMagenta", modifiers = ["Bold"] }
table_header = { fg = "Blue" }
selection = { modifiers = ["Bold", "Reversed"] }